w3c-ccg/vcalm

- docs/vc-http-api.yml
> Small typo fixes

- docs/test-suite/index.html
Demonstrate how conformance test report can be generated on the fly for any vendor assuming some refactoring of the test suite.
> Add experimental realtime test report

- README.md
Additions to the top level repository readme so that it is clear what lives where along with stated goals for the repository.  Just trying to make this repo a little easier to approach if you haven't been living in the ccg calls/mailing lists/etc.
The info I have added is based on reading the repo, previous issues, mailing list discussions, etc. but is based on my understanding, so I may have missed something.  Please add additional commentary on items that I may need to add or reword.
> Add some additional information to the top level readme for clarity

- docs/README.md
Initial fill out on the readme to address #101
> initial updates to the readme for clarity

- packages/vc-http-api-test-server/__fixtures__/credentials/case-10.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-12.json
Adds sample fixtures from the [vaccination vocabulary](https://w3id.org/vaccination)
> feat: add vaccination certificate test fixture

- packages/plugfest-2020/vendors/trustbloc/index.js
- packages/vc-http-api-test-server/config/SecureKey.js
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
> chore: update trustbloc DID config for test

- packages/vc-http-api-test-server/config/SecureKey.js
- packages/vc-http-api-test-server/config/index.js
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
> chore: update trustbloc DID config for new plugfest suite

- docs/vc-http-api.yml
This operation is used to derive a credential for selective disclosure from another verifiable credential.
> Add deriveCredential operation

- packages/vc-http-api-test-server/config/DigitalBazaar.js
Updates Digital Bazaar's endpoints.
> Update Digital Bazaar configuration.

- packages/vc-http-api-test-server/__fixtures__/credentials/index.js
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/index.js
- packages/vc-http-api-test-server/__tests__/issueCredential.spec.js
- packages/vc-http-api-test-server/__tests__/verifyCredential.spec.js
Adds the fixture file name to the interop test descriptions
> feat: add fixture filename to interop test cases

- packages/vc-http-api-test-server/config/index.js
- packages/vc-http-api-test-server/config/mesur.io.js
Adding a test config in for mesur.io
> Add mesur.io to test configs

- packages/vc-http-api-test-server/config/Mavennet.js
- packages/vc-http-api-test-server/config/index.js
updates Mavennet Config to add them to test suite.
> add mavennet to config

- packages/vc-http-api-test-server/config/SecureKey.js
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
> chore: update securekey config

- packages/vc-http-api-test-server/config/Spruce.js
- packages/vc-http-api-test-server/config/index.js
This adds config for Spruce's implementation, [DIDKit](https://github.com/spruceid/didkit/).
> Add Spruce config

- packages/vc-http-api-test-server/__fixtures__/credentials/case-11.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-12.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-13.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-14.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-15.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-16.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-17.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-18.json
- packages/vc-http-api-test-server/__fixtures__/credentials/case-19.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-22.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-23.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-24.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-25.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-26.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-27.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-28.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-29.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-30.json
If I've missed anything, apologies! NB @therecanbeonlyone1969
See also https://hackmd.io/RC-hj5zrRV2kVPlULLU93g?view#Crib-Sheet-4-Spherity-Interop-Flow
> Test fixtures from eComm credentials & VCs

- index.html
Added contracts 70RSAT20T00000003 and 70RSAT20T00000033.
> Government contract references added

- docs/versions/v0.0.2/vc-http-api.yml
Making VC mandatory attrs required on the schema too.
If some are required on the (non-verifiable) Credential, they can be made mandatory there instead.
> Added required element on VerifiableCredentials

- docs/components/Presentation.yml
Reference to the VC schema, not just an object
> vc-reference

- docs/components/Credential.yml
- docs/components/DeriveCredentialOptions.yml
- docs/components/IssueCredentialOptions.yml
- docs/components/Issuer.yml
- docs/components/LinkedDataProof.yml
- docs/components/PresentCredentialOptions.yml
- docs/components/Presentation.yml
- docs/components/VerifiableCredential.yml
- docs/components/VerifiablePresentation.yml
- docs/components/VerificationResult.yml
- docs/components/VerifyOptions.yml
this addresses: #212  and is a small housekeeping PR
> [Chore] Bump Version number in current working files

- index.html
This PR is a partial alternate to PR #226. This particular PR is a non-normative introductory section to the Authorization section in the specification. It sets expectations, but delegates the normative language to subsections (in separate PRs). It differs from PR #226 in a few ways:
* It is only the introduction, the specific normative sections on authz mechanisms will be in separate PRs.
* It does not say anything about RAR (separate PR).
* It does not say anything about OAuth2.0 (separate PR).
* It does not say anything about delegation (separate PR).
* It does not say anything about GNAP (separate PR).
* It does not say anything about forbidden methods (separate PR).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/pull/228.html" title="Last updated on Sep 25, …
> Add introduction to authorization section.

- README.md
cherrypicked from previous disastrous git branch
> Add meeting info (and hardwrap lines)

- components/IssueCredentialOptions.yml
- components/PresentCredentialOptions.yml
- components/VerifyOptions.yml
Addresses https://github.com/w3c-ccg/vc-api/issues/67.
@clehner
> Fix description of default "verificationMethod"

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/matthieubosquet/vc-api/pull/303.html" title="Last updated on Sep 15, 2022, 2:21 PM UTC (6a8bfbb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/303/d275b08...matthieubosquet:6a8bfbb.html" title="Last updated on Sep 15, 2022, 2:21 PM UTC (6a8bfbb)">Diff</a>
> Typo in VC API spec

- holder.yml
Addresses: https://github.com/w3c-ccg/vc-api/issues/305
This a DRAFT because the description needs bikeshedding.
> Add 404 to exchanges/exchange-id/transaction-id responses.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/vc-api/pull/319.html" title="Last updated on Oct 28, 2022, 2:52 PM UTC (70e3266)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/319/c37438c...aljones15:70e3266.html" title="Last updated on Oct 28, 2022, 2:52 PM UTC (70e3266)">Diff</a>
> Fix bug: continue should use POST not PUT in index.html.

- holder.yml
Note: this should be merged after this PR: https://github.com/w3c-ccg/vc-api/pull/323
Related: https://github.com/w3c-ccg/vc-api/issues/311
> Exchanges Continue response can be anyOf VPResponse or VPRequest.

- index.html
This PR adds a "Design Goals and Rationale" section to the VC API specification. It's just the start of a few items that we are designing for, I'm sure there are others that will need to be added in time.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 21, 2023, 6:18 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c-ccg%2Fvc-api%2F3cde330594928a5936c7013b2e36a624d0035201%2Findex.html …
> Add Design Goals and Rationale

- CODEOWNERS
I think I should be removed from here, since I haven't really had time in the last few months to participate much in this work item or review issues and PRs.
However, as Danube Tech, we will continue to implement this in our products and happily participate in test suites.
> Remove me from CODEOWNERS

- .gitignore
It either needs committing or ignoring and since it's not there now...I assume it needs ignoring.﻿
> Ignore package-lock.json.

- index.html
Fix #244
***
<a href="https://pr-preview.s3.amazonaws.com/BigBlueHat/vc-api/pull/351.html" title="Last updated on Dec 12, 2023, 9:47 PM UTC (dfff0f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/351/bf79360...BigBlueHat:dfff0f6.html" title="Last updated on Dec 12, 2023, 9:47 PM UTC (dfff0f6)">Diff</a>
> Add text about base URL. Fix #244.

- components/DeriveCredentialOptions.yml
- components/IssueCredentialOptions.yml
Initial fix for #371 
string might not be correct but assuming string to fix OAS rendering
> fix(Issue & Derive Options): adding items type

- components/VerifyCredentialResult.yml
> rename verifiableCredential in verifiCredentialResult to credential

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/390.html" title="Last updated on Jun 4, 2024, 6:32 PM UTC (869d918)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/390/cb6494c...869d918.html" title="Last updated on Jun 4, 2024, 6:32 PM UTC (869d918)">Diff</a>
> Add discussion of challenge/exchange lifetime.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-api/pull/420.html" title="Last updated on Sep 11, 2024, 8:31 PM UTC (1f82fb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/420/7cd48f1...TallTed:1f82fb1.html" title="Last updated on Sep 11, 2024, 8:31 PM UTC (1f82fb1)">Diff</a>
> fix a singular/plural disagreement

- holder.yml
> Return object with the results property.

- index.html
- issuer.yml
Addresses #232
***
<a href="https://pr-preview.s3.amazonaws.com/OpSecId/vc-api/pull/464.html" title="Last updated on Mar 11, 2025, 7:15 PM UTC (6ff4de8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/464/9fe7325...OpSecId:6ff4de8.html" title="Last updated on Mar 11, 2025, 7:15 PM UTC (6ff4de8)">Diff</a>
> Add guidelines for status retrieval

- index.html
Addresses #343
***
<a href="https://pr-preview.s3.amazonaws.com/OpSecId/vc-api/pull/465.html" title="Last updated on Apr 1, 2025, 7:08 PM UTC (434bf72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/465/9fe7325...OpSecId:434bf72.html" title="Last updated on Apr 1, 2025, 7:08 PM UTC (434bf72)">Diff</a>
> Add api design guidelines

- index.html
Addresses #379
***
<a href="https://pr-preview.s3.amazonaws.com/OpSecId/vc-api/pull/466.html" title="Last updated on Apr 1, 2025, 7:20 PM UTC (ef9feb8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/466/7b033ca...OpSecId:ef9feb8.html" title="Last updated on Apr 1, 2025, 7:20 PM UTC (ef9feb8)">Diff</a>
> Add validation guidance

- components/DataIntegrityProofWithChallenge.yml
- components/VerifiablePresentation.yml
This PR is an attempt to address issue #402 by ensuring that challenge/domain is not used in VCs.
> Ensure that challenge/domain isn't used in VCs, only in VPs.

- exchanges.yml
This PR addresses [this comment](https://github.com/w3c-ccg/vc-api/issues/453#issuecomment-2970845122) from Issue #453 by accepting 201 status responses for exchange and workflow creations.
> Accept 201 status response for exchange and workflow creation.

- index.html
This PR addresses issue #439 by adding clarifying text to explain that VC API workflows are designed to support more than just linear step sequences.
- Added explanatory text in the "Workflows and Exchanges" section clarifying that workflows support both linear sequences and complex patterns
- Explicitly mentioned support for branching logic and repeated steps
- `index.html` - Modified the workflow definition paragraph in the "Workflows and Exchanges" section
This PR implements the first part of issue #439. The second part (explaining HOW step templates enable branching logic and repeated steps) requires deeper understanding of the implementation approach discussed in https://github.com/w3c-ccg/vc-api/issues/457. 
**Note:** Currently I'm reviewing discussion in …
> Add workflow branching intent clarification

- components/VerifyPresentationOptions.yml
- components/VerifyPresentationResult.yml
- verifier.yml
This PR is an attempt to address issue #376 by modernizing the result of presentation verification.
> Modernize verify presentation result.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-api/pull/500.html" title="Last updated on Jul 24, 2025, 6:32 PM UTC (6b51d48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/500/c616311...TallTed:6b51d48.html" title="Last updated on Jul 24, 2025, 6:32 PM UTC (6b51d48)">Diff</a>
> fix some grammar, whitespace, markup in index.html

- exchanges.yml
This PR is an attempt to address issue #403 by adding a presentationSchema option to a workflow step.
> Add ability to specify presentationSchema to workflow step.

- index.html
This PR is an attempt to address issue #344 by specifying a section that describes how this specification is different from other protocol specifications in the ecosystem.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/pull/529.html" title="Last updated on Sep 13, 2025, 6:22 PM UTC (f9cb84e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/529/6b772ac...f9cb84e.html" title="Last updated on Sep 13, 2025, 6:22 PM UTC (f9cb84e)">Diff</a>
> Add Relationship to Other Specifications section.

- index.html
This PR is an attempt to address issue #523 by adding a Secure Coding Practices and an Other Security Considerations section to the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/pull/535.html" title="Last updated on Sep 14, 2025, 5:24 PM UTC (db1ef0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/535/ad1424c...db1ef0b.html" title="Last updated on Sep 14, 2025, 5:24 PM UTC (db1ef0b)">Diff</a>
> Add Secure Coding Practices section.
