w3c-ccg/vcalm

- packages/plugfest-2020/package-lock.json
- packages/plugfest-2020/package.json
When running the test suite on macOS (10.15.7), I would see the below TypeError following the test results. This would result in a non-zero exit status even if all tests passed.
In attempting to create a minimal test case for `jest-html-reporter`, I found that just updating it to v3 gets rid of the error. So I present this PR to update the dependency version.
<details>
<summary>Error output before updating</summary>
```
$ npm run test:dock
[...]
Ran all test suites.
internal/fs/utils.js:781
throw new ERR_INVALID_ARG_TYPE(
^
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of XMLElement
at writeFile (fs.js:1436:5)
at go$writeFile (/Users/cel/src/vc-http-api/packages/plugfest-2020/node_modules …
```
> Update jest-html-reporter to fix test suite on macOS

- docs/vc-http-api.yml
- docs/versions/v0.0.1/index.html
- docs/versions/v0.0.1/vc-http-api.yml
This PR builds on the previous one which created "v0.0.2-unstable"
It attempts to formally adopt the controller naming convention, as described here:
https://restfulapi.net/resource-naming/
> A controller resource models a procedural concept. Controller resources are like executable functions, with parameters and return values; inputs and outputs.
This aligns best with the existing APIs, and also avoids some of the complaints regarding REST / HTTP specific interfaces as functional style routes are easier to translate to other transports.
> Adopt controller pattern

- docs/versions/v0.0.1/index.html
- docs/versions/v0.0.1/vc-http-api.yml
This moves the "latest" version to the archive, and opens the door for breaking changes in "v0.0.2-unstable"
No changes have been made at this time to "v0.0.2-unstable"
> Archive version 0.0.1

- packages/plugfest-2020/.gitignore
- packages/plugfest-2020/help.js
- packages/plugfest-2020/plugfest-2020.spec.js
- packages/plugfest-2020/utilities/oauth.js
This PR adds basic support for obtaining an access_token for request authorization via the client credentials. Has been tested locally but our environment is not stood up yet so I have not checked in our vendor config that will use this feature. Ideally we need to support the injection of secrets for each vendors config via GH secrets rather than checking it into the repo directly.
To use this feature, add this config element to your vendor config
```
{
...,
request_authorization_config: {
type: "oauth2-client-credentials",
token_endpoint: " https://idp.com/oauth/token",
client_id: "xxxxxxxx",
client_secret: "xxxxxxxxxx",
audience: "optional-audience-constraint"
}
}
```
Fixes #86
> OAuth2.0 Client Credentials Request Authorization Support

- docs/vc-http-api.yml
This PR proposes support for issuing a verifiable credential that includes a credential status, whereby one valid type of credential status implementation is [RevocationList2020](https://w3c-ccg.github.io/vc-status-rl-2020/).
The intended behaviour is that if the credentialStatusMethod property is present in the issue options section of the request, then the requestor is asking the issuer to issue a verifiable credential featuring a status using the method specified in the request.
Outstanding questions for review
- Are there options beyond just the credential status that should be communicated in the issuance request? E.g the initial state of the credentials status? Which revocation list (if applicable) the credential status should be issued against?
- How does a requestor know what …
> feat: add support for credentialStatus on credential issue

- packages/vc-http-api-test-server/services/jest/cli.js
- packages/vc-http-api-test-server/services/jest/utilities.js
Set a default test timeout for jest of 15 secs as some did resolution requests that were using remote resolvers were taking sometime to resolve. Also fixed generating the JSON based report summary for the tests.
> Minor test suite improvements

- docs/vc-http-api.yml
This PR adds a credential issuer API for managing an update to the status of an issued credential.
*Outstanding Questions*
- ~~How should the status property relate to the type property in the request? Are we assuming that the type sets the valid enumeration of values for status?~~ Yes
- ~~Is the credentialId the id of the issued credential?~~ Yes
> feat: add update credential status endpoint

- docs/fixtures/README.md
- docs/fixtures/revocationList.json
This PR is the first part of adding verify tests for revocation. In order to keep the revocation tests based on fixtures controlled by the test suite we need to host the associated revocation lists with the test suite, this PR adds a test fixture that will be fetch-able by vendors infrastructure in order to perform the revocation check.
> feat: add hostable revocation list as fixture

- packages/vc-http-api-test-server/__tests__/issueCredential.spec.js
~~PR is dependent on #110 #115 being merged ahead.~~
~~If you want to review before rebase, please just review [60cd0f5](https://github.com/w3c-ccg/vc-http-api/commit/60cd0f51c9b35fe5b58c12ac630ed97088499d5f).~~
The PR adds two new *optional* test cases to the VC HTTP Issuance API for issuing a credential with a credential status.
Has been test against our infrastructure but we have not exposed ours yet so no vendors in the current test suite are hitting these tests. A vendor can express support for optional feature by including the following in their `issueCredentialConfiguration` element
```
{
credentialStatusesSupported: [ "RevocationList2020Status" ]
}
```
> feat: add issue credential with revocation status tests

- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-14.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-15.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/index.js
- packages/vc-http-api-test-server/__tests__/verifyCredential.spec.js
- packages/vc-http-api-test-server/services/utilities.js
Adds a new test case (13) with a positive and negative test for checking whether a verifiers API can correctly detect an active and revoked credential status in accordance with `RevocationList2020Status`
> feat: add basic verify credentialStatus tests

- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-16.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-17.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-18.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-19.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-20.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-21.json
- packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/index.js
- packages/vc-http-api-test-server/__tests__/verifyCredential.spec.js
- packages/vc-http-api-test-server/services/utilities.js
PR dependent on #124 being merged ahead.
This PR adds optional test fixtures for the verifyCredential endpoint test cases for those who support BbsBlsSignature2020
> feat: add bbs fixtures

- packages/vc-http-api-test-server/__tests__/issueCredential.spec.js
- packages/vc-http-api-test-server/__tests__/verifyCredential.spec.js
- packages/vc-http-api-test-server/config/DanubeTech.js
- packages/vc-http-api-test-server/config/DigitalBazaar.js
- packages/vc-http-api-test-server/config/Dock.js
- packages/vc-http-api-test-server/config/Factom.js
- packages/vc-http-api-test-server/config/Mavennet.js
- packages/vc-http-api-test-server/config/SICPA.js
- packages/vc-http-api-test-server/config/SecureKey.js
- packages/vc-http-api-test-server/config/Transmute.js
- packages/vc-http-api-test-server/config/TrybeID.js
PR dependent on #128 being merged ahead.
Adds in the ability to formally recognise the signature suite that the credential will be issued under for a configured issuer. Also adds in multiple new negative test cases for the verifyCredential interop test cases.
> feat: signature suite agility

- packages/vc-http-api-test-server/__tests__/issueCredential.spec.js
"assertionMethod" doesn't exist as an option for `/credentials/issue`.
See https://github.com/w3c-ccg/vc-http-api/blob/master/docs/vc-http-api.yml#L221.
Fixes https://github.com/w3c-ccg/vc-http-api/issues/112.
> Change "assertionMethod" option to "verificationMethod" in issueCredential test.

- packages/vc-http-api-test-server/services/jest/cli.js
> Increase test timeout to one minute

- common.js
- index.html
- terms.html
This implements a decision made on a previous call:
https://w3c-ccg.github.io/meetings/2021-05-06-vchttpapi/#resolution-1
RESOLUTION: Create 1 ReSpec specification based on the OAS files, in addition to separating the existing OAS files into modular components.
> Add initial structure for VC HTTP API specification.

- docs/components/IssueCredentialOptions.yml
- docs/components/PresentCredentialOptions.yml
Signature suite [Ethereum EIP712 Signature 2021](https://uport-project.github.io/ethereum-eip712-signature-2021-spec/) (proposed work item: https://github.com/w3c-ccg/community/issues/194) does not define a new verification method but only a signing method (proof type), and is meant to be used with existing verification methods `EcdsaSecp256k1VerificationKey2019` or `EcdsaSecp256k1RecoveryMethod2020`. For proof creation with `vc-http-api`, the `verificationMethod` option of the issue/present credential options is then no longer sufficient to identify the type of proof to create, since there is not a one-to-one correspondance of verification method type to proof type. This PR adds a type option for use in situations such as this where there is more than one type of proof that could be …
> Add proof type issue/present option

- index.html
This PR specifies that OAuth 2.0 and OAuth 2.0 bearer tokens can be used as an authorization protocol and access token format.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/pull/231.html" title="Last updated on Sep 26, 2021, 12:03 AM UTC (901d266)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/231/ed6a27e...901d266.html" title="Last updated on Sep 26, 2021, 12:03 AM UTC (901d266)">Diff</a>
> Add section on OAuth 2.0 and bearer tokens.

- index.html
This PR adds a section on authorization protocols that are forbidden for use with this API.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/pull/229.html" title="Last updated on Sep 27, 2021, 8:47 PM UTC (2845c35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/229/0f39732...2845c35.html" title="Last updated on Sep 27, 2021, 8:47 PM UTC (2845c35)">Diff</a>
> Add section on forbidden authorization.

- common.js
- components/Presentation.yml
- index.html
This PR adds an ability to ReSpec to generate sections of the specification directly from the OAS files. This ensures that the root of truth continues to be the OAS files, but that those are also translated into human-readable normative ReSpec descriptions.
This is the first iteration of this experimental feature. There is still a lot of formatting that needs to be done with the JSON Schema sections to ReSpec text, but that is fairly straight-forward to do and will just take a bit of time to get formatted into the shape that we want.
You can preview what all of this looks like here: https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/pull/233.html#the-vc-http-api
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-http-api/pull/233.html" title="Last updated on Sep 26, 2021, …
> Add ReSpec auto-generator from OAS files.

- README.md
Fixed broken API links: had the old /vc-http-api/ instead of the new /vc-api/
> Fixed broken API links

- fixtures/revocationList.json
Address #236
A corresponding PR to update the verifiable credentials using the revocation list is here: https://github.com/w3c-ccg/vc-api-test-suite/pull/10.
This uses a new key I generated locally, as I have not access to the existing key. Is this a correct approach?
> Regenerate revocation list credential for new URL

- components/VerifyOptions.yml
Fix #68 as proposed in https://github.com/w3c-ccg/vc-api/issues/68#issuecomment-964581687 and discussed on the [2021-11-09 VC API work item call](https://w3c-ccg.github.io/meetings/2021-11-09-vcapi/).
Related: #253 (Remove verificationMethod from VerifyOptions)
> Remove created from VerifyOptions

- components/LinkedDataProof.yml
Addresses https://github.com/w3c-ccg/vc-api/issues/194.
> Add "challenge","domain","nonce" to LinkedDataProof.

- components/LinkedDataProof.yml
Addresses https://github.com/w3c-ccg/vc-api/issues/194.
> Add "proofValue" to LinkedDataProof.

- components/VerifyOptions.yml
When verifying, being able to specify a verificationMethod as an option can be dangerous, see discussion in https://github.com/w3c-ccg/vc-api/pull/248.
> Remove verificationMethod from VerifyOptions

- index.html
This section adds a section on issuance automation via workflows. This is what creates the ability to do things like AutoRefresh2021. If folks are ok with the non-normative text here (the concept), then I plan to add normative text in a separate PR to try and establish something that is testable.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/254.html" title="Last updated on Jan 7, 2022, 4:53 PM UTC (67ab5d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/254/1714ec7...67ab5d7.html" title="Last updated on Jan 7, 2022, 4:53 PM UTC (67ab5d7)">Diff</a>
> Add section on automation via workflows.

- components/ErrorResponse.yml
- components/parameters/path/ExchangeId.yml
- components/parameters/path/TransactionUuid.yml
- holder.yml
- index.html
This PR is based on ACTIONS requested to be taken on the last VC API call (see summary at top of transcription): https://w3c-ccg.github.io/meetings/2022-02-01-vcapi/
The goals here are to:
I've done the first of three items and will halt here for feedback from the Traceability work item group to ensure that this meets their expectations from the call two days ago.
The target merge window is in 7 days, after the VC API call next week.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/258.html" title="Last updated on Feb 9, 2022, 9:45 PM UTC (fc195cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/258/6b8c865...fc195cd.html" title="Last updated on Feb 9, 2022, 9:45 PM UTC (fc195cd)">Diff</a>
> Refactor presentation endpoints into exchange endpoints

- components/parameters/path/TransactionId.yml
- components/parameters/path/TransactionUuid.yml
- holder.yml
- index.html
This PR expands the range of transaction identifiers to allow for multibase (base58btc and base64url) encoded 128-bit numbers.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/262.html" title="Last updated on Feb 16, 2022, 11:05 PM UTC (d667a0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/262/7b43c72...d667a0c.html" title="Last updated on Feb 16, 2022, 11:05 PM UTC (d667a0c)">Diff</a>
> Enable transaction identifiers to be multibase encoded 128-bit numbers.

- index.html
This PR addresses the following ACTION I took last month: https://w3c-ccg.github.io/meetings/2022-02-15-vcapi/#action-1
> ACTION: Manu to articulate why transaction-id is an expression of a 128-bit number that is meaningful to the server, but opaque to the client, and how we might open up the range of values later.
I chose to not articulate that it was a 128-bit number since I've heard some rumblings that folks would like the option that it can be a different/larger value.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/269.html" title="Last updated on Mar 13, 2022, 3:35 PM UTC (7b3180c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/269/bfa77bd...7b3180c.html" title="Last updated on Mar 13, 2022, 3:35 PM UTC (7b3180c)">Diff</a>
> Clarify that exchange-id/transaction-id are opaque to client.

- components/VerifiablePresentationRequest.yml
- index.html
Changes DIDAuth to `DIDAuthentication`
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/vc-api/pull/317.html" title="Last updated on Oct 21, 2022, 4:20 PM UTC (41c7554)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/317/9219bd6...aljones15:41c7554.html" title="Last updated on Oct 21, 2022, 4:20 PM UTC (41c7554)">Diff</a>
> Change DIDAuth to DIDAuthentication.

- index.html
Fixes #297 by renaming "App" terminology to "Coordinator".
/cc @jandrieu or @eric-schuh -- we need to be able to edit the image to change the labeling in the ecosystem image. Can either of you rework the image you have into a shared editing medium (Google Draw) or provide an SVG that we can render/edit in the spec?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/308.html" title="Last updated on Oct 9, 2022, 11:26 PM UTC (7513cc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/308/9219bd6...7513cc2.html" title="Last updated on Oct 9, 2022, 11:26 PM UTC (7513cc2)">Diff</a>
> Rename "App" to "Coordinator".

- index.html
There seems to be a typo in the "[Get a specific Presentation](https://w3c-ccg.github.io/vc-api/#get-a-specific-presentation)" section.
The exchange discovery endpoint is missing from the "[Presenting](https://w3c-ccg.github.io/vc-api/#presenting)" summary.
***
<a href="https://pr-preview.s3.amazonaws.com/matthieubosquet/vc-api/pull/309.html" title="Last updated on Oct 11, 2022, 9:23 AM UTC (2294aca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/309/9219bd6...matthieubosquet:2294aca.html" title="Last updated on Oct 11, 2022, 9:23 AM UTC (2294aca)">Diff</a>
> Fix Presentation endpoints

- README.md
- package.json
Adds basic instructions on how to serve the `index.html` and not just the api documentation.
> Add serveIndex & docs on serving the index.html.

- issuer.yml
- respec-oas.js
Instead of returning the Vc as the response body itself we now return an object of the form:
```js
{
verifiableCredential: {
...Vc
}
}
```
This does not change the property used to issue a credential which remains `credential` as the group seems to have settled on `credential` for an unsigned Vc and `verifiableCredential` for a signed Vc with a proof. Returning the Vc in the property `verifiableCredential` also opens up the possibility of return error codes and other error information which should make testing easier.
Related: https://github.com/w3c-ccg/vc-api/issues/291
This does not add metadata as consensus on what that metadata should look like has not been reached.
+1 to using a metadata pattern similar to did resolution.
> POST /credentials/issue should return an object with property verifiableCredential

- index.html
This corrects a mistake where the exchange examples didn't match the `exchanges continue` schema.
Addresses: https://github.com/w3c-ccg/vc-api/issues/311
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/vc-api/pull/322.html" title="Last updated on Nov 4, 2022, 3:38 PM UTC (024d3cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/322/f12d687...aljones15:024d3cd.html" title="Last updated on Nov 4, 2022, 3:38 PM UTC (024d3cd)">Diff</a>
> Add verifiablePresentation to exchanges examples.

- components/ErrorResponse.yml
- components/Issuer.yml
Corrects a small bug where schema properties with out a description had `undefined` in them in the `index.html`.
> Adds a description to issuer.id & the error response.

- holder.yml
This is a draft and for discussion purposes only.
It does not represent the consensus of the group.
This adds 404 responses to the following endpoints:
- GET /presentations/{id} - Gets a presentation or verifiable presentation by ID
- DELETE /credentials/{id} - Delete a credential or verifiable credential by ID
- GET /presentations/{id}
- DELETE /presentations/{id}
> Add 404 as a response for GET/DELETE credentials/{id} and same for VPs

- index.html
- terms.html
This PR adds an introductory section to the VC API specification including the reasoning behind having VC APIs defined that are both internal to a single security domain and ones used to communicate between two different security domains.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 21, 2023, 6:16 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c-ccg%2Fvc-api%2F93b26f2ee8b3dc3e727 …
> Expand introductory section to include purpose of spec.

- components/SecuritySchemes.yml
- holder.yml
- issuer.yml
- verifier.yml
This PR fixes linting errors in the OAS files. OAS linting requires that every endpoint define security properties and at least one server endpoint. Reviewers should pay specific attention to this PR because it does add authorization mechanisms available on each endpoint, including noAuth, didAuth, oAuth2, and zCap (since the current set of implementers support at least one of those mechanisms, if not multiple). Setting this PR to draft so we can discuss.
The intent of this PR is NOT to establish the correct authz mechanisms for each endpoint, that will be done in a future PR. The goal here is to get "close enough" and then fine tune the authz mechanisms in a future PR. Do not take the authz mechanisms provided as anything more than a work in progress at this point in time.
> Fix linting errors in OAS files.

- common.js
- index.html
This pull request is an attempt to address issue #186 by adding a Privacy Considerations section on avoiding "phoning home".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/349.html" title="Last updated on Jan 9, 2024, 8:32 PM UTC (bf0e3ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/349/5c50923...bf0e3ee.html" title="Last updated on Jan 9, 2024, 8:32 PM UTC (bf0e3ee)">Diff</a>
> Add Privacy Considerations section on "phone home".

- components/DataIntegrityProof.yml
- components/DeriveCredentialOptions.yml
- components/IssueCredentialOptions.yml
- components/PresentCredentialOptions.yml
- components/VerifiableCredential.yml
- components/VerifiablePresentation.yml
- components/VerifyOptions.yml
This PR attempts to address issue #194 by renaming the legacy "LinkedDataProof" mechanism to the new "DataIntegrityProof" mechanism being standardized by W3C's VCWG.
> Rename LinkedDataProof to DataIntegrityProof.

- CONTRIBUTING.md
This PR adds informal tips on how to submit a PR.
I'm not 100% sure that these tips are useful enough to justify their maintenance effort if the PR guidance changes, but some of it may be. Glad to take on feedback on this point.
This PR has no associated github issue.
TODO:
> add PR tips to CONTRIBUTING.md

- README.md
> Fix, clarify, or update links in README.

- index.html
This PR is an attempt to address issue #252 by adding a section on delegation proposed by @agropper.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/359.html" title="Last updated on Jan 23, 2024, 7:18 PM UTC (098da50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/359/4ce8393...098da50.html" title="Last updated on Jan 23, 2024, 7:18 PM UTC (098da50)">Diff</a>
> Add section on delegation.

- index.html
This PR is an attempt to address issue #276 by adding a Security Considerations section on deletion.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/360.html" title="Last updated on Jan 23, 2024, 7:20 PM UTC (2236468)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/360/6a4579c...2236468.html" title="Last updated on Jan 23, 2024, 7:20 PM UTC (2236468)">Diff</a>
> Add Security Considerations section on deletion.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/362.html" title="Last updated on Feb 19, 2024, 7:21 PM UTC (67bc74b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/362/f634b54...67bc74b.html" title="Last updated on Feb 19, 2024, 7:21 PM UTC (67bc74b)">Diff</a>
> Add discussion of authorization use cases

- components/VerificationResult.yml
- components/VerifyOptions.yml
- respec-oas.js
PR to address https://github.com/w3c-ccg/vc-api/issues/207
TODO:
> Add returnCredential option to VerifyOptions

- index.html
Defines the mechanism by which OAuth2 can be used as an authorization technology for VC APIs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/369.html" title="Last updated on Feb 27, 2024, 8:21 PM UTC (6f7949d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/369/8a94c1f...6f7949d.html" title="Last updated on Feb 27, 2024, 8:21 PM UTC (6f7949d)">Diff</a>
> 301 define oauth2 authorization mechanism

- index.html
Add section explicitly stating that properties in `options` are not required for any endpoint, but that configuration may disallow clients from using specific options.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/370.html" title="Last updated on Mar 5, 2024, 8:10 PM UTC (d720962)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/370/8a94c1f...d720962.html" title="Last updated on Mar 5, 2024, 8:10 PM UTC (d720962)">Diff</a>
> Add general discussion of `options`.

- components/Challenge.yml
- components/IssueCredentialOptions.yml
- holder.yml
- index.html
- verifier.yml
- add challenge creation endpoint `\challenges`
- return `ChallengeVerificationMetadata` when `options.challenge` passed so client can track number of times challenge used
- remove passing `options.challenge` and `options.domain` to incorrect endpoints
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/373.html" title="Last updated on Mar 19, 2024, 6:52 PM UTC (4f34389)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/373/15a3e9b...4f34389.html" title="Last updated on Mar 19, 2024, 6:52 PM UTC (4f34389)">Diff</a>
> Add /challenges endpoint.

- index.html
Adds normative text requiring that requests/responses have `Content-Type` set to `application/json`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/377.html" title="Last updated on Mar 26, 2024, 7:25 PM UTC (7a75f58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/377/15a3e9b...7a75f58.html" title="Last updated on Mar 26, 2024, 7:25 PM UTC (7a75f58)">Diff</a>
> Require `Content-Type: application/json` HTTP header.

- components/Challenge.yml
- components/CreatePresentationOptions.yml
- components/DeriveCredentialOptions.yml
- components/IssueCredentialOptions.yml
- components/VerifyCredentialOptions.yml
- components/VerifyPresentationOptions.yml
- holder.yml
- verifier.yml
Forked off #373 
tackles #318 
Merge conflicts will be cleaned up once  once #373 is merged in.
Challenge changes are not intended to be reviewed in this PR, but are remnants from forking off #373. 
1. Updates `IssueCredentialOptions` to remove `created`, and updates the example
2. Updates `DeriveCredentialOptions` to add `selectivePointers`
3. Removes `VerifyOptions` this has now been split into:
4.  `VerifyCredentialOptions`: this currently only has `returnCredential` which is based on what the current spec shows.
5. `VerifyPresentationOptions`: this currently has the properties `domain` and `challenge`. The issue mentions adding `proofPurpose`, but I wasn't sure, iirc the `proofPurpose` of a presentation is always `authentication`. if that is not true happy to update the PR. The Spec …
> cleanup issueCredentialOptions and VerifyOptions

- holder.yml
- index.html
Updates all references from proving a presentations to become creating a presentations. 
Changes endpoint from POST `presentations/prove` to POST `presentations`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/378.html" title="Last updated on Mar 26, 2024, 8:00 PM UTC (6d48c56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/378/ffe5571...6d48c56.html" title="Last updated on Mar 26, 2024, 8:00 PM UTC (6d48c56)">Diff</a>
> update endpoint from Prove to create

- components/parameters/path/LocalExchangeId.yml
- components/parameters/path/LocalWorkflowId.yml
- exchanges.html
- exchanges.yml
- index.html
- respec-oas.js
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/382.html" title="Last updated on May 29, 2024, 8:35 PM UTC (dee75b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/382/5099989...dee75b2.html" title="Last updated on May 29, 2024, 8:35 PM UTC (dee75b2)">Diff</a>
> Add workflows and exchanges endpoints.

- exchanges.yml
- holder.yml
- index.html
- issuer.yml
- respec-oas.js
- verifier.yml
- versions/v0.0.2/vc-api.yml
This PR looks to resolve https://github.com/w3c-ccg/vc-api/issues/285 
A section has been added to the "The VC API " section of the document called "API Component Overview". This section summarizes all endpoints in the VC-API, grouping them by the component the endpoint is expected to live on, along with a table for each of these components that lists the API endpoint, as well as the component that is the expected caller of the endpoint. 
The workflow/exchanges endpoints are not currently indexed but should be added after the following PR is completed:
https://github.com/w3c-ccg/vc-api/pull/382
***
<a href="https://pr-preview.s3.amazonaws.com/eric-schuh/vc-api/pull/384.html" title="Last updated on Jun 4, 2024, 5:16 PM UTC (d67e052)">Preview</a> | <a …
> Adding section that details API Endpoints by Component

- holder.yml
- index.html
- issuer.yml
- verifier.yml
Addresses #383 #340 #331 and #141 
Standing questions:
[RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html) or [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)?
What should the relationship with [verification algorithms](https://w3c.github.io/vc-data-model/#algorithms) from the spec be?
Should we define specific error codes for each [ProblemDetails](https://w3c.github.io/vc-data-model/#problem-details)?
Is it fair to assume that if an errors are returned the credential is not verified but if only warning are returned it is verified? (see list of error/warnings in the PR for details)
Keyword [status](https://datatracker.ietf.org/doc/html/rfc7807#section-3.1) vs code...
***
<a href="https://pr-preview.s3.amazonaws.com/OpSecId/vc-api/pull/389.html" title="Last updated on Jun 18, …
> Add error handling section

- index.html
- adds text requiring implementations throw an error on receiving data, options, or option values not understood by the endpoint.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/394.html" title="Last updated on Jun 25, 2024, 6:37 PM UTC (1023ee6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/394/494f0a2...1023ee6.html" title="Last updated on Jun 25, 2024, 6:37 PM UTC (1023ee6)">Diff</a>
> Add section for handling unknown options/data.

- components/EnvelopedVerifiableCredential.yml
- components/IssueCredentialSuccess.yml
This PR adds [EnvelopedVerifiableCredential](https://www.w3.org/TR/vc-data-model-2.0/#enveloped-verifiable-credentials) as an allowed schema in the `IssueCredentialSuccess` response object.
The impetus for this PR is #357 .
> Issuing EnvelopedVerifiableCredentials

- exchanges.yml
- allows a client to get information about what the server will need to complete an exchange before making calls that might result in issuance.
> Allow initiation of exchange to contain a VPR.

- index.html
Fixes: https://github.com/w3c-ccg/vc-api/issues/404
***
<a href="https://pr-preview.s3.amazonaws.com/laysakura/vc-api/pull/408.html" title="Last updated on Jul 23, 2024, 7:54 PM UTC (0e35a25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/408/066f030...laysakura:0e35a25.html" title="Last updated on Jul 23, 2024, 7:54 PM UTC (0e35a25)">Diff</a>
> docs(fix): move paragraphs that should be in the Storage Services section from the Workflow Service section

- exchanges.yml
Addresses #393
Replace `workflowId` in request/response and returned a workflow object.
> Added workflow response object to workflow creation call

- components/EnvelopedVerifiablePresentation.yml
- holder.yml
This PR continues the implementation of #357 . It is similar to #397 but for `EnvelopedVerifiablePresentation` rather than `EnvelopedVerifiableCredential`
> Add EvelopedVerifiablePresentation as Create Presentation response

- index.html
Following up on https://github.com/w3c-ccg/vc-api/issues/357#issuecomment-2327254214, this PR adds notes to indicate that `Enveloped` objects can be used to support different credential and presentation media types.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/417.html" title="Last updated on Sep 10, 2024, 6:39 PM UTC (233edeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/417/f2ae3bd...233edeb.html" title="Last updated on Sep 10, 2024, 6:39 PM UTC (233edeb)">Diff</a>
> Add notes to Issue Credential and Create Presentation regarding different media types

- index.html
This PR adds some much needed exposition on workflows and exchanges.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/416.html" title="Last updated on Sep 11, 2024, 7:37 PM UTC (b028d5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/416/f2ae3bd...b028d5a.html" title="Last updated on Sep 11, 2024, 7:37 PM UTC (b028d5a)">Diff</a>
> Add workflows and exchange exposition.

- components/ProblemDetail.yml
- components/ProblemDetails.yml
- components/VerifyCredentialOptions.yml
- components/VerifyCredentialResult.yml
- index.html
- Created a new `ProblemDetails` object. 
- Modified the credentials/verify options and response
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/418.html" title="Last updated on Oct 8, 2024, 7:05 PM UTC (d969201)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/418/f2ae3bd...d969201.html" title="Last updated on Oct 8, 2024, 7:05 PM UTC (d969201)">Diff</a>
> 414 problem details response

- components/Credential.yml
- respec-oas.js
Features:
- Adds support for `type: array` to `oneOf` schemas
- Adds `proof` to issue credential API endpoint schema
- Redefines UnsecuredCredential  in components to allow it to optionally have a proof
Addresses some, but not all of this issue: https://github.com/w3c-ccg/vc-api/issues/422
> Add proof to schema for credentials intended for issuance

- index.html
This PR:
- Creates a new "Service Instances" section with text to address #419
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/426.html" title="Last updated on Oct 22, 2024, 7:40 PM UTC (f81d2c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/426/26ee3f6...f81d2c5.html" title="Last updated on Oct 22, 2024, 7:40 PM UTC (f81d2c5)">Diff</a>
> Add Service Instances Configuration text

- index.html
As this example is a single exchange, the exchange id should be the same in both participate calls.
See issue #425 for discussion.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/427.html" title="Last updated on Oct 9, 2024, 1:31 PM UTC (c81c87b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/427/26ee3f6...c81c87b.html" title="Last updated on Oct 9, 2024, 1:31 PM UTC (c81c87b)">Diff</a>
> Fix local exchangeId in exchange example.

- exchanges.yml
Can't track `state` if it's not there. 😃
> Add `state` & `variables` to GetExhangeResponse.

- index.html
Adds a new "Options Extensiblity" sub section with the information discussed here: https://github.com/w3c-ccg/vc-api/issues/335#issuecomment-1478481131
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/435.html" title="Last updated on Dec 17, 2024, 8:47 PM UTC (f582120)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/435/5aff850...f582120.html" title="Last updated on Dec 17, 2024, 8:47 PM UTC (f582120)">Diff</a>
> Add Options Extensibility section

- index.html
Addresses #432 . Includes guidance on how asynchronous issuance may be implemented.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/441.html" title="Last updated on Feb 4, 2025, 8:26 PM UTC (aa1ff96)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/441/ace3da6...aa1ff96.html" title="Last updated on Feb 4, 2025, 8:26 PM UTC (aa1ff96)">Diff</a>
> Clarify that exchanges are short-lived

- index.html
Addresses #425 . This is currently only relevant to the workflows and exchanges APIs so it is added to that section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/442.html" title="Last updated on Feb 4, 2025, 8:33 PM UTC (b681e2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/442/ace3da6...b681e2f.html" title="Last updated on Feb 4, 2025, 8:33 PM UTC (b681e2f)">Diff</a>
> Clarify the distinction between local and fully qualified IDs.

- index.html
This PR attempts to address issue #267 by documenting how service instance configuration works.
Fixes #267.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/443.html" title="Last updated on Feb 18, 2025, 2:19 PM UTC (55c75d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/443/ace3da6...55c75d5.html" title="Last updated on Feb 18, 2025, 2:19 PM UTC (55c75d5)">Diff</a>
> Elaborate on service configuration

- index.html
Addresses #437
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/445.html" title="Last updated on Feb 25, 2025, 8:15 PM UTC (80217f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/445/ace3da6...80217f6.html" title="Last updated on Feb 25, 2025, 8:15 PM UTC (80217f6)">Diff</a>
> Add a recommendation section and a security section for payload sizes

- exchanges.yml
This PR addresses Issue #452 by removing unnecessary intermediate "config" property in workflow request/response body definitions.
**NOTE:** I am still seeing the `config` property in the OpenAPI spec when I run it locally. Anyone know why that might be?
> Remove "config" property from workflow definitions.

- exchanges.yml
This PR addresses Issue #454 by adding the `active` state to the exchange creation response.
> Add `active` state to exchange creation response.

- exchanges.yml
This PR addresses Issue #455 by converting the format of the `createChallenge` workflow step property from `string` to `boolean`.
> Convert `createChallenge` property from `string` to `boolean`.

- exchanges.yml
This PR address Issue #447 by converting `sequence` format from `string` to `number`.
> Convert sequence format from `string` to `number`.

- exchanges.yml
This PR addresses Issue #453 by embedding the exchange creation response in the `exchange` property and renaming `exchangeId` to `id`.
@dlongley As it was [your recommendation](https://github.com/w3c-ccg/vc-api/issues/453#issuecomment-2663880455) to return the exchange in `exchange` during exchange creation (which is apparently consistent with the exchange retrieval response format), should I create an issue to do the same for workflow creation? If so, it seems the general pattern will be to include the body parameters directly in the request, and return it in an intermediate property in the response (e.g., `exchange`, `workflow`). Before we move forward, it would be good to confirm this pattern generally.
> Embed exchange creation response in `exchange` property.

- respec-oas.js
- verifier.yml
Partially addresses #424 . The objective of the PR is to add support for verifying EnvelopedVCs and EnvelopedVPs. This is done by adding enveloped VCs and VPs as possible schemas to the credentials/verify and persentations/verify endpoints respectively.
> Verify Enveloped Credentials and Enveloped Presentations

- exchanges.yml
- index.html
This PR addresses Issue #434 by fixing a number of issues with the exchange creation spec.
***
<a href="https://pr-preview.s3.amazonaws.com/kezike/vc-api/pull/474.html" title="Last updated on Apr 22, 2025, 7:25 PM UTC (029fe8b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/474/9aa0e53...kezike:029fe8b.html" title="Last updated on Apr 22, 2025, 7:25 PM UTC (029fe8b)">Diff</a>
> Fix spec for exchange creation.

- index.html
This PR is an attempt to address issue #337 by stating when `proof` can be attached to a provided `credential`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/478.html" title="Last updated on May 20, 2025, 7:50 PM UTC (65b2e01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/478/1f3de7e...65b2e01.html" title="Last updated on May 20, 2025, 7:50 PM UTC (65b2e01)">Diff</a>
> Clarify when proofs can be appended to by issuance endpoint.

- components/VerifiableCredentialResponse.yml
- holder.yml
- index.html
- issuer.yml
This PR is an attempt to address issue #398 by returning an object containing a `verifiableCredential`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/481.html" title="Last updated on Jun 3, 2025, 7:22 PM UTC (2c12a38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/481/23ab19c...2c12a38.html" title="Last updated on Jun 3, 2025, 7:22 PM UTC (2c12a38)">Diff</a>
> Ensure that GET /credentials/{{id}} includes object that contains `verifiableCredential`.

- exchanges.yml
- index.html
This PR is an attempt to address issue #421 by adding the .../protocols endpoint to exchanges.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/489.html" title="Last updated on Jul 26, 2025, 9:43 PM UTC (ef7fac9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/489/28eb39e...ef7fac9.html" title="Last updated on Jul 26, 2025, 9:43 PM UTC (ef7fac9)">Diff</a>
> Add /protocols endpoint to specific exchanges.

- holder.yml
- index.html
This PR is an attempt to address issue #407 by adding a credential deletion section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/491.html" title="Last updated on Jul 27, 2025, 9:23 PM UTC (7dcfcd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/491/dbf8a82...7dcfcd3.html" title="Last updated on Jul 27, 2025, 9:23 PM UTC (7dcfcd3)">Diff</a>
> Add credential deletion section.

- components/Credential.yml
- index.html
This PR addresses **https://github.com/w3c-ccg/vc-api/issues/422** by clarifying how the `/credentials/issue` endpoint handles credentials with existing proofs as agreed upon in the 2025-05-27 call.
**Background**
This PR replaces PR #495, which had corrupted commit history due to a rebase issue that lost proper attribution. I apologize for my mistake - this clean branch preserves everyone's contributions with correct authorship.
**Individual Contributions**
- @bparth24: [Add proof chain and set documentation to credential issuance](https://github.com/bparth24/vc-api/commit/5e13014dda494355176d8242d208001290e9779a)
- @TallTed: [contribution - Fix grammatical issues in issue credential section](https://github.com/bparth24/vc-api/commit/5f11d00c23270cccd8ebaf04bd1ce93e9102a3b2)
- @dlongley: …
> Add proof chain and set documentation to credential issuance

- components/VerifyPresentationOptions.yml
- index.html
- verifier.yml
- Updates specification text to explicitly state VP verification includes all contained VCs by default
- Updates POST /presentations/verify endpoint to reflect comprehensive verification of presentations and contained credentials
- Adds extensibility for implementer options to disable credential verification for debugging purposes
- Documents compositional API design enabling use of /credentials/verify for individual credential verification when VP credential checking is disabled
- Clarifies verification vs validation boundaries with business rules handled by calling applications
- Enhances HTTP response descriptions in /presentations/verify endpoint to clarify process success vs verification outcomes
To my understanding above updates are sufficient.
----
**Updates are highlighted**
---- …
> Clarify VP verification scope and add implementer flexibility.

- index.html
This PR attempts to establish the conformance classes that we want to support in the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/pull/533.html" title="Last updated on Sep 13, 2025, 6:44 PM UTC (fa14056)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/533/6b772ac...fa14056.html" title="Last updated on Sep 13, 2025, 6:44 PM UTC (fa14056)">Diff</a>
> Add issuer, verifier, and holder service conformance classes.

- oas.yaml
Add two endpoints, along with their required components. These are:
- /interactions/{interactionId}
- /{inviteId}/invite-request/response
A couple of things I would like double checked due to my unfamiliarity with yaml and OAS:
1. In the component table, for the "Protocols" object, is the "otherFutureAPI" property appropriate? I believe we aren't planning on specifying a supported list of protocols, so I was trying to show that the object is extendable.
2. In the summary of the {inviteId}/invite-request/response, I tried to capture a note from @dlongley that in the case someone implements the entire VCALM we would expect inviteID to be an exchangeId. Is this the right spot for this kind of message or should it be moved elsewhere?
> Added yaml to support the interaction mechanism endpoints

- index.html
This PR is an attempt to address issue #539 by warning against putting protocol details in the interaction URL.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/pull/554.html" title="Last updated on Sep 27, 2025, 8:08 PM UTC (fcb2f84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vcalm/554/2a522e0...fcb2f84.html" title="Last updated on Sep 27, 2025, 8:08 PM UTC (fcb2f84)">Diff</a>
> Warn against putting protocol details in interaction URL.
